name: Pocco_Restrict

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [labeled, synchronize, opened, ready_for_review]

concurrency:
  if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

jobs:
  ci:
    # 実行条件まとめ
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on issue $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (example)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

        #初回テスト時プルリクエストする際に　@ci-run とコメント。